
MODEL_NAME = "Qwen/Qwen3-4B-Instruct-2507"
K_TOKENS = 128
TAU = 0
MAX_BACKTRACKS = 3
NUM_SAMPLES = 50
FINAL_ANSWER_PREFIX = "####"
STEP_SEPARATOR = "\n\n"
DEBUG = False
VERBOSE = True
EPSILON = 1e-3
SEED = 69